// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFeG1BDk41i1lhEic_5SWwgzYjfqROck',
    appId: '1:948842718018:web:4809516a3662bc954d5edb',
    messagingSenderId: '948842718018',
    projectId: 'parcel-counting-system',
    authDomain: 'parcel-counting-system.firebaseapp.com',
    storageBucket: 'parcel-counting-system.appspot.com',
    measurementId: 'G-G8W02ZVH0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR89IabvGmy7B5Jhpq2NU4C3Axem2gxoA',
    appId: '1:948842718018:android:fcb2c734f884d0bc4d5edb',
    messagingSenderId: '948842718018',
    projectId: 'parcel-counting-system',
    storageBucket: 'parcel-counting-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9a6mZ6w47PCzvCDvyb_do042qtspWbE',
    appId: '1:948842718018:ios:600c2d7f17133c414d5edb',
    messagingSenderId: '948842718018',
    projectId: 'parcel-counting-system',
    storageBucket: 'parcel-counting-system.appspot.com',
    iosBundleId: 'com.example.parcelCountingSystem',
  );
}
